# Generated by Django 2.1 on 2019-03-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='choice',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
