# Generated by Django 2.1.1 on 2018-09-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.CharField(choices=[('Computer Science', 'cse'), ('Information Technology', 'it'), ('Electrical', 'electrical'), ('Civil', 'civil'), ('Electronics', 'electronics')], default='Computer Science', max_length=255),
        ),
    ]
