# Generated by Django 2.1.1 on 2018-09-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20180924_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='description',
        ),
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Electronics', 'Electronics')], default='Computer Science', max_length=255),
        ),
    ]
